# This question is asked by Google. 
# You are given two strings, s and t which only 
# consist of lowercase letters. t is generated by 
# shuffling the letters in s as well as potentially 
# adding an additional random character. 
# Return the letter that was randomly added to t 
# if it exists, otherwise, return ’  ‘.
# Note: You may assume that at most one additional 
# character can be added to t.

# Ex: Given the following strings...

# s = "foobar", t = "barfoot", return 't'
# s = "ide", t = "idea", return 'a'
# s = "coding", t "ingcod", return ''

s, t = "foobar", "barfoot" #return t
s1, t1 = "ide", "idea" #return 'a'
s2, t2 = "coding", "ingcod" #return ''

def spot_the_difference(s, t):
    s_map, t_map = {}, {}
    for x in s:
        if s in s_map:
            s_map[x] += 1
        else:
            s_map[x] = 0
    for x in t:
        if t in t_map:
            t_map[x] += 1
        else:
            t_map[x] = 0
    for x in t_map:
        # print(x)
        if x not in s_map:
            return x
    return ' '
print(spot_the_difference(s2, t2))